
'use server';
/**
 * @fileOverview An AI-powered flow to find biddable projects based on a user query.
 *
 * ---
 * !! DEBUGGING MODE ACTIVATED !!
 * This flow completely bypasses AI to test the data path. It directly
 * searches the project database and returns the results.
 * ---
 */

import { ai } from '@/ai/genkit';
import {
  FindBiddableProjectsInput,
  FindBiddableProjectsOutput,
  BiddableProjectSchema,
  FindBiddableProjectsInputSchema,
} from './find-biddable-projects-shared';
import { listProjects } from '@/services/mock-data';
import { z } from 'zod';

export async function findBiddableProjects(
  input: FindBiddableProjectsInput
): Promise<FindBiddableProjectsOutput> {
  return findBiddableProjectsFlow(input);
}

const findBiddableProjectsFlow = ai.defineFlow(
  {
    name: 'findBiddableProjectsFlow',
    inputSchema: FindBiddableProjectsInputSchema,
    outputSchema: z.object({
        dataSource: z.enum(['DATABASE', 'AI_GENERATED']),
        projects: z.array(BiddableProjectSchema),
    }),
  },
  async (input) => {
    console.log(`[DEBUG MODE] Bypassing AI. Searching directly for: "${input.query}"`);
    
    // Step 1: Directly call the data service with the user's query.
    const matchedProjects = await listProjects({ query: input.query });

    if (!matchedProjects || matchedProjects.length === 0) {
      console.log('[DEBUG MODE] No projects found.');
      return { projects: [], dataSource: 'DATABASE' };
    }

    console.log(`[DEBUG MODE] Found ${matchedProjects.length} projects.`);

    // Step 2: Map the direct results to the final output schema.
    const results: FindBiddableProjectsOutput = {
      projects: matchedProjects.map(p => ({
        // Spread the original project data
        id: p.id, 
        name: p.name,
        organization: p.organization,
        type: p.type,
        budget: p.budget,
        address: p.address,
        contactPerson: p.contactPerson,
        phone: p.phone,
        documentUrl: p.documentUrl,
        
        // Add placeholder data for fields that are normally generated by the AI.
        analysis: "AI IS BYPASSED FOR DEBUGGING. This is a direct data result.",
        winProbability: 50,
        estimatedProfit: 15,
        historicalAnalysis: {
            successCount: 0,
            failureCount: 0,
            pastWinners: [],
        },
        reasonForWinning: "N/A (AI Bypassed)",
        recommendedBidPrice: p.budget || "N/A",
      })),
      dataSource: 'DATABASE',
    };

    return results;
  }
);
