type Project {
  id: String!
  name: String!
  type: String
  organization: String
  budget: String
  address: String
  contact_person: String
  phone: String
  document_url: String
}

type Contact {
  id: String!
  name: String!
  type: String
  email: String
  phone: String
  address: String
  contact_person: String
}

type Query {
  listProjects(query: String): [Project] @sql(
    query: """
    SELECT
      id,
      name,
      type,
      organization,
      budget,
      address,
      contact_person,
      phone,
      document_url
    FROM
      projects
    WHERE
      ($1::text IS NULL OR name ILIKE $1 OR organization ILIKE $1)
    ORDER BY
      budget DESC NULLS LAST
    LIMIT 20;
    """,
    parameters: [{
      name: "query"
    }]
  )

  listContacts(type: String, searchQuery: String): [Contact] @sql(
    query: """
    SELECT
        id,
        name,
        type,
        email,
        phone,
        address,
        contact_person
    FROM
        contacts
    WHERE
        ($1::text IS NULL OR type = $1)
    AND ($2::text IS NULL OR name ILIKE $2 OR email ILIKE $2 OR contact_person ILIKE $2)
    ORDER BY name;
    """,
    parameters: [{
      name: "type"
    },{
      name: "searchQuery"
    }]
  )
}
